// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAoBzy_vJzzULv9apD7QD506bBC0UIRLw',
    appId: '1:161246912398:web:a99d6acbdc2254e181cedf',
    messagingSenderId: '161246912398',
    projectId: 'hadith-premium',
    authDomain: 'hadith-premium.firebaseapp.com',
    storageBucket: 'hadith-premium.firebasestorage.app',
    measurementId: 'G-K5VMCPJ7F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhwjQvrcwI_xs0RzpABataSRa3hj9AqKw',
    appId: '1:161246912398:android:9ee3c5ea6009e94881cedf',
    messagingSenderId: '161246912398',
    projectId: 'hadith-premium',
    storageBucket: 'hadith-premium.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDffalQBTbeO2nVossMqPoN10QVCeENsYo',
    appId: '1:161246912398:ios:1689919c42e4b57c81cedf',
    messagingSenderId: '161246912398',
    projectId: 'hadith-premium',
    storageBucket: 'hadith-premium.firebasestorage.app',
    iosClientId: '161246912398-agp97fanlqidnail9r8t0ngp76db1tou.apps.googleusercontent.com',
    iosBundleId: 'com.example.hadithPremium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDffalQBTbeO2nVossMqPoN10QVCeENsYo',
    appId: '1:161246912398:ios:1689919c42e4b57c81cedf',
    messagingSenderId: '161246912398',
    projectId: 'hadith-premium',
    storageBucket: 'hadith-premium.firebasestorage.app',
    iosClientId: '161246912398-agp97fanlqidnail9r8t0ngp76db1tou.apps.googleusercontent.com',
    iosBundleId: 'com.example.hadithPremium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAoBzy_vJzzULv9apD7QD506bBC0UIRLw',
    appId: '1:161246912398:web:ce99a5838acbc01f81cedf',
    messagingSenderId: '161246912398',
    projectId: 'hadith-premium',
    authDomain: 'hadith-premium.firebaseapp.com',
    storageBucket: 'hadith-premium.firebasestorage.app',
    measurementId: 'G-XDSD4PVG1P',
  );
}
